sudo: required
branches:
  only:
    - master
    - next
    - /20(1[7-9]|2[0-9])[0-1][0-9][0-3][0-9]/
    - /^greenkeeper/.*$/

services: docker

language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: standars check
      script: npm run test
    - stage: build tools
      script: ./travis-build.sh
    - stage: build data containers
      script: node build.js > /dev/null