name: Process master push or pr
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run linters
        run: npm run test
  docker-push:
    if: github.ref == 'refs/heads/master'
    needs:
      - lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set time zone to Europe/Bucharest
        uses: zcong1993/setup-timezone@master
        with:
          timezone: "Europe/Bucharest"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: |
          npm install
          node build.js
